### ISSUE TITLE
Authentication with service account

### ISSUE THREAD

**Issue by leszek-sieminski-at-brainly** [jamescottrill/googleTagManageR#2]
Hello James!

Thanks for this package! {googleTagManageR} proved to be invaluable in my work and I love it :)

I'm wondering if it would be possible to implement also authentication with service account? It's [covered](https://github.com/MarkEdmondson1234/googleAnalyticsR/blob/master/R/auth.R) by {googleAnalyticsR} and I think that also by {gargle}, so it should be possible.

Thanks!
Leszek

**Comment by jamescottrill** [comment]
Hi Leszek,
Yes, definitely possible. I'll have a look at the implementation but I don't think it will be too difficult to set up. I've got a bit of time in the next couple of weeks so should be able to dive into this then. I'll keep this issue updated.

James

**Comment by jamescottrill** [comment]
@leszek-sieminski-at-brainly This has been added to 0.2.0 and has been submitted to CRAN, once that's approved it will be available, alternatively you can install it from github using `remotes::install_github("jamescottrill/googleTagManageR")`.
